# SPDX-FileCopyrightText: © 2026 Decompollaborate
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "address_space"
version = "0.1.0"
edition = "2018"
description = ""
authors = [
    "Anghelo Carvajal <angheloalf95@gmail.com>",
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Decompollaborate/address_space"
readme = "README.md"
keywords = [
]
categories = [
    "no-std",
    "no-std::no-alloc",
]

# Use https://github.com/foresterre/cargo-msrv to check the MSRV
# ```
# cargo install cargo-msrv --locked --force
# cargo msrv find
# ```
# rust-version = "1.83"

[features]
default = []

std = []

[dependencies]

[profile.release]
debug = true
